### ISSUE TITLE
Unhandled interrupt (2), exception...

### ISSUE THREAD

**Issue by matthiasbock** [interoberlin/Baumhaus-Firmware-MyNewt#10]
Commit: 9ca6603482762863d6d391cf9163a56d7a70e55b

UART console output of the alarmlight app:
https://www.youtube.com/watch?v=DdrDJp7dtGU

```sh
000000 Assert @ 0xce93
000000 Unhandled interrupt (2), exception sp 0x20001488
000000  r0:0x00000000  r1:0x00020b47  r2:0x80000000  r3:0xe000ed00
000000  r4:0x0000ce93  r5:0x00021e24  r6:0x00000000  r7:0x00008a39
000000  r8:0xffffffff  r9:0xffffffff r10:0xffffffff r11:0xffffffff
000000 r12:0x00000000  lr:0x00008aeb  pc:0x000081c0 psr:0x81000000
000000 ICSR:0x00421002
```

as opposed to the bleprph app:
https://www.youtube.com/watch?v=SQxTQ2ljUg8

**Comment by matthiasbock** [comment]
The following "magic" lines must be present in the target's syscfg.yml in order for it to work:
```yml
syscfg.vals:
    # OS main/default task
    OS_MAIN_STACK_SIZE: 468

    # Lots of smaller mbufs are required for newtmgr using typical BLE ATT MTU
    # values.
    MSYS_1_BLOCK_COUNT: 22
    MSYS_1_BLOCK_SIZE: 110
```
