### ISSUE TITLE
Must configure either external or synthesized 32.768 xtal source

### ISSUE THREAD

**Issue by matthiasbock** [interoberlin/Baumhaus-Firmware-MyNewt#5]
```sh
$ newt build floorsensor
...
Compiling repos/apache-mynewt-core/hw/mcu/nordic/nrf51xxx/src/hal_spi.c
Error: repos/apache-mynewt-core/hw/mcu/nordic/nrf51xxx/src/hal_os_tick.c:35:2: error: #error "Must configure either external or synthesized 32.768 xtal source"
 #error "Must configure either external or synthesized 32.768 xtal source"
  ^
```

Baumhaus-Firmware: a6c6b2be03c793f934138d6087e09a0749723aae
MyNewt: 88fcd354f9a24a734004b3fd641c20e45eb2d1c1
nrf51+openocd bsp: f9f25908e04f44a89891444b0ef0d7cd62df1da0

**Comment by matthiasbock** [comment]
* repos/apache-mynewt-core/hw/mcu/nordic/nrf51xxx/src/hal_os_tick.c:35
````C
...
/* Must have external 32.768 crystal or used synthesized */
#if (MYNEWT_VAL(XTAL_32768) == 1) && (MYNEWT_VAL(XTAL_32768_SYNTH) == 1)
#error "Cannot configure both external and synthesized 32.768 xtal sources"
#endif

#if (MYNEWT_VAL(XTAL_32768) == 0) && (MYNEWT_VAL(XTAL_32768_SYNTH) == 0)
#error "Must configure either external or synthesized 32.768 xtal source"
#endif
...
````

**Comment by matthiasbock** [comment]
* apps/floorsensor/syscfg.yml
```yml
...
syscfg.vals:
...
    XTAL_32768: 1
...
```

**Comment by matthiasbock** [comment]
Dirty fix:
Manually add the XTAL_32768, that apparently can't be resolved, to
* repos/apache-mynewt-core/hw/mcu/nordic/nrf51xxx/syscfg.yml
```yml
...

# Package: hw/bsp/nrf52dk

syscfg.defs:
    MCU_FLASH_MIN_WRITE_SIZE:
        description: >
            Specifies the required alignment for internal flash writes.
            Used internally by the newt tool.
        value: 1

    MCU_DCDC_ENABLED:
        description: >
            Specifies whether or not to enable DC/DC regulator. This requires
            external circuitry so is defined to be zero by default and
            expected to be overridden by the BSP.
        value: 0

    XTAL_32768:
        value: 1

```
